### ISSUE TITLE
Create an "occurrences" built-in filter for core

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-extensions#10]
This filter extension should provide the current occurrences/refresh filter logic in sensu-plugin Sensu::Plugin::Handler. This extension can also replace Sensu Enterprise `handle_when` filter.

**Comment by fessyfoo** [comment]
consider the potential requirement of filtering the resolve event only in the case that at least one create was not filtered.  https://github.com/sensu-plugins/sensu-plugin/pull/142#issuecomment-233121674

**Comment by portertech** [comment]
@fessyfoo occurrence filtering is fundamentally flawed, specially with limited access to status history. We are going to add another built-in extension that leverages event last_ok and last_state_change as a better alternative :+1:

**Comment by fessyfoo** [comment]
cool.  I'm interested to see the algorithm.   :)
