### ISSUE TITLE
Question : How to package Sensu Extensions for distribution

### ISSUE THREAD

**Issue by warmfusion** [sensu/sensu-extensions#6]
I'm working on a sensu-extension (https://github.com/warmfusion/sensu-extension-snmptrap/tree/sensu_plugin_format ) but don't know how best to distribute it.

The sensu-plugins project has taken an approach to deliver checks as executable scripts on users paths, but extensions (as far as I understand it) need to live inside the sensu /etc/sensu/extensions path?

Anyone got a suggestion for how best to deliver this code through a gem?

**Comment by portertech** [comment]
@warmfusion: you could use native packages to deliver the file(s) to `/etc/sensu/extensions`.

**Comment by warmfusion** [comment]
That's a shame, I was hoping there'd be a mechanism that'd let extensions get either discovered, or otherwise delivered into specific paths without having to create native packages for each distribution...

**Comment by portertech** [comment]
@warmfusion I spent the morning hacking on https://github.com/sensu/sensu-extensions/pull/12 with @cwjohnston :+1:

**Comment by portertech** [comment]
This Sensu extensions project is up and running (to an extent)! 

https://github.com/sensu-extensions

Installation is now done via `sensu-install -e` :+1: 

An extension project repository template exists at: https://github.com/sensu-extensions/template

An example project: https://github.com/sensu-extensions/sensu-extensions-statsd
