### ISSUE TITLE
Invalid Gem v1.4.0 test suite

### ISSUE THREAD

**Issue by paramite** [sensu/sensu-extensions#9]
Test suite shipped within gem v1.4.0 is missing following symlink, which made tests to fail:

spec/assets/extensions/extensions_symlinked

**Comment by roock** [comment]
I think I'm having a related issue during installation of sensu-extensions 1.5.0:

Exception `Gem::Package::PathError' at /usr/lib/ruby/2.3.0/rubygems/package.rb:424 - installing into parent path /usr/lib/ruby/gems/2.3.0/gems/extensions_symlinked of /usr/lib/ruby/gems/2.3.0/gems/sensu-extensions-1.5.0 is not allowed
ERROR:  While executing gem ... (Gem::Package::PathError)
    installing into parent path /usr/lib/ruby/gems/2.3.0/gems/extensions_symlinked of /usr/lib/ruby/gems/2.3.0/gems/sensu-extensions-1.5.0 is not allowed

**Comment by portertech** [comment]
This was due to a Rubygems version bug on 2.3.0. Upgrading Rubygems seems to fix this :+1:
